name: flutter_vision
description: Plugin for managing Yolov5, Yolov8 and Tesseract v5 accessing with TensorFlow Lite 2.x. Support object detection, segmentation and OCR on Android. iOS, Working in progress.
  
version: 1.1.4

homepage: https://github.com/vladiH/flutter_vision

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.vladih.computer_vision.flutter_vision
        pluginClass: FlutterVisionPlugin
      ios:
        pluginClass: FlutterVisionPlugin